### ISSUE TITLE
(question) I think this is broken for pixel sizes != 1

### ISSUE THREAD

**Issue by L-Sherry** [CCDirectLink/extendable-severed-heads#1]
I don't have a simple way to test this mod, but i think that pixel sizes != 1 will break this mod.

Please correct me if i'm wrong, but my general understanding of the game's code indicate that the ig.Image's LoadListeners are called after resizing and filtering, which is typically done with a pixel size != 1. I don't have a simple way to test this, through.

If that is is correct, the simplest way would be to scale the coordinate calculations by ig.system.scale.

**Comment by ghost** [comment]
I'll test it.

**Comment by ghost** [comment]
I had my pixel size set to 4 when I made this. I just tested it with 1 and it works fine.

**Comment by L-Sherry** [comment]
oh it seems ig.system.scale does not depend on pixel size, sorry for the noise.
