### ISSUE TITLE
Appears as v1.0.0 in-game

### ISSUE THREAD

**Issue by PLMMJ-FH** [CCDirectLink/extendable-severed-heads#6]
When I load the game, the mod says on the Mods list that it's 1.0.0 even though it has been updated to 1.1.0, hampering my ability to play with Xenon's Triblader Mod as that one requires 1.1.0, unaware of this issue.
![CCModBug](https://github.com/CCDirectLink/extendable-severed-heads/assets/159862724/82cbfe18-5b15-4a7a-8438-fb7481632a68)

**Comment by PLMMJ-FH** [comment]
Was able to self-fix by replacing "1.0.0" with "1.1.0" in the ccmod.json and package.json files myself.

**Comment by elluminance** [comment]
Download the newest ccmod/zip.

There was an issue with the original release where the version was accidentally not updated.

**Comment by PLMMJ-FH** [comment]
Thanks.
